package jp.ac.it_college.std.s22025.fragmentbasicaltest


data class City(
    val name: String,
    val q: String
)

val cityList = listOf(
    City("北海道(札幌)","Sapporo"),
    City("青森","Aomori"),
    City("岩手(盛岡)","Morioka"),
    City("宮城(仙台)","Sendai"),
    City("秋田","Akita"),
    City("山形","Yamagata"),
    City("福島","Fukushima"),
    City("茨城(水戸)","Mito"),
    City("栃木(宇都宮)","Utsunomiya"),
    City("群馬(前橋)","Maebashi"),
    City("埼玉(さいたま)","Saitama"),
    City("千葉","Chiba"),
    City("東京","Tokyo"),
    City("神奈川(横浜)","Yokohama"),
    City("新潟","Nigata"),
    City("富山","Toyama"),
    City("石川(金沢)","Kanazawa"),
    City("福井","Fukui"),
    City("山梨(甲府)","Kofu"),
    City("長野","Nagano"),
    City("岐阜","Gifu"),
    City("静岡","Shizuoka"),
    City("愛知(名古屋)","Aichi"),
    City("三重(津)","Tsu"),
    City("滋賀(大津)","Otsu"),
    City("京都", "Kyoto"),
    City("大阪", "Osaka"),
    City("兵庫", "Hyogo"),
    City("奈良", "Nara"),
    City("和歌山", "Wakayama"),
    City("鳥取","Tottori"),
    City("島根(松江)","Matsue"),
    City("岡山","Okayama"),
    City("広島","Hiroshima"),
    City("山口","Yamaguchi"),
    City("徳島","Tokushima"),
    City("香川(高松)","Takamatsu"),
    City("愛媛(松山)","Matsuyama"),
    City("高知","Kochi"),
    City("福岡","Fukuoka"),
    City("佐賀","Saga"),
    City("長崎","Nagasaki"),
    City("熊本","Kumamoto"),
    City("大分","Oita"),
    City("宮崎","Miyazaki"),
    City("鹿児島","Kagoshima"),
    City("沖縄", "Okinawa"),
)